/*
#E1 - Estructura básica
#E2 - Add stage CI Test
#E4 - Add function runInDocker
#E5 - Add CI Build image

*/

def runInDocker(String image, Closure body) {
  docker.image(image).inside {
    body()
  }
}

pipeline {
  agent any

  options {
    timestamps()
    disableConcurrentBuilds()
  }

  environment {
    IMAGE_NAME = "contrerasadr/devops-training-python-app:${env.BUILD_NUMBER}"
  }

  stages {
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
        echo "Branch: ${env.BRANCH_NAME}"
      }
    }

    stage('CI - Test') {
      steps {
        script {
          runInDocker('python:3.6-slim') {
            sh 'pip install -r requirements.txt'
            sh 'pytest -q'
          }
        }
      }
    }

    stage('CI - Build image') {
      steps {
        script {
          docker.build(env.IMAGE_NAME, '-f Dockerfile .')
        }
      }
    }
  }
}
