version: "3.7"

services:
  app:
    #image: contrerasadr/devops-training-python-app:0.0.1
    image: ${IMAGE_NAME}
    #build: 
    #  context: .
    #  dockerfile: devops/Dockerfile
    #container_name: my-flask-app-dc  --> eliminamos para que Docker Compose genere nombres automáticamente
    restart: unless-stopped
    networks:
      - scalian_training
    environment:
      DB_USER: root
      DB_PWD: rootpwd
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: knights
    depends_on:
      db:
        condition: service_healthy
    ports:
      #- "5001:5000" --> eliminamos para que asigne puerto dinámicamente

  
  db:
    image: postgres:16-alpine
    #container_name: my-flask-app-db  --> eliminamos para que Docker Compose genere los nombres y evitar colisión
    restart: always
    ports:
      #- "32000:5432" --> eliminamos para que asigne puerto dinámicamente
    environment:
      POSTGRES_PASSWORD: rootpwd
      POSTGRES_USER: root
      POSTGRES_DB: knights
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
    networks:
      scalian_training:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d knights"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  scalian_training:
    driver: bridge
  
volumes:
  dbdata:
